"""
Write methodology/PARAMETERS_BY_ASSET.md directly from the case-study CSV registers,
so every value and its rationale shown to readers is the value the code uses.

    python scripts/make_parameter_tables.py
"""

from __future__ import annotations

import pathlib as _pl
import sys as _sys
_sys.path.insert(0, str(_pl.Path(__file__).resolve().parents[1]))

import csv
from pathlib import Path

from costofdelay.model import HarvestBand, LikelihoodBand, ValueBand

ROOT = Path(__file__).resolve().parents[1]
TITLES = {
    "mosip": "MOSIP (national identity platform)",
    "fineract": "Apache Fineract (core banking)",
    "openmrs": "OpenMRS (medical records)",
    "online_boutique": "Online Boutique (demo web shop; mock data)",
}


def usd(x):
    return "0" if x == 0 else (f"{x/1e6:g}M" if x >= 1e6 else f"{x/1e3:g}k")


def main():
    L = ["# Parameter values and rationale, by asset", "",
         "Generated by `scripts/make_parameter_tables.py` from `case_studies/*/asset_register.csv`.",
         "Every value here is the value the code scores; none is retyped. Provenance of **every** row is",
         "`ASSUMED_FROM_PUBLIC_DOCS` unless marked `POSITED` (an invented asset, excluded from all results).",
         "See `PARAMETERS.md` for how each parameter and band is defined and anchored.", ""]
    for key, title in TITLES.items():
        rows = list(csv.DictReader(open(ROOT / "case_studies" / key / "asset_register.csv", encoding="utf-8")))
        L += [f"## {title}", "",
              "| ID | Asset | Loss V | Hazard λ | Lifetime L (y) | Lock | Recordable h | Turnover τ | Provenance | Rationale |",
              "|---|---|---|---|---|---|---|---|---|---|"]
        for r in rows:
            v = ValueBand[r["value_band"]].usd
            lam = LikelihoodBand[r["likelihood_band"]].per_year
            h = HarvestBand[r["harvest_band"]].fraction
            tau = r["turnover_per_year"] or "1 (default)"
            why = (r["rationale"] or "").replace("|", "/")
            ev = (r.get("evidence_for_zeroing") or "").replace("|", "/")
            if ev:
                why = f"**Zeroing evidence:** {ev} {why}".strip()
            L.append(f"| {r['asset_id']} | {r['name']} | ${usd(v)} ({r['value_band']}) | {lam:g} ({r['likelihood_band']}) | "
                     f"{float(r['data_lifetime_years']):g} | {r['protection_class']} | {h:g} ({r['harvest_band']}) | {tau} | "
                     f"{r['provenance']} | {why} |")
        L.append("")
    (ROOT / "methodology" / "PARAMETERS_BY_ASSET.md").write_text("\n".join(L), encoding="utf-8")
    print("wrote methodology/PARAMETERS_BY_ASSET.md")


if __name__ == "__main__":
    main()
